eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/,http://peer3:9003/eureka/
spring:
  profiles:
    active: peer1
---
spring:
  profiles: peer1
server:
  port: 9001
eureka:
  instance:
    hostname: peer1

---
spring:
  profiles: peer2
server:
  port: 9002
eureka:
  instance:
    hostname: peer2

---
spring:
  profiles: peer3
server:
  port: 9003
eureka:
  instance:
    hostname: peer3